kafka:
  clusters:
    -
      name: local
      bootstrapServers: kafka:9092
      schemaRegistry: http://localhost:8085
      schemaRegistryAuth:
        username: username
        password: password
      metrics:
        port: 9997
        type: JMX