replicaCount: 1

zookeeper:
  image: "wurstmeister/zookeeper"
  port: 2181
  replicas: 1
  service:
    type: ClusterIP
    port: 2181
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard"
    accessModes:
      - ReadWriteOnce
    annotations: {}
    existingClaim: ""

kafka:
  image: "confluentinc/cp-kafka:latest"
  port: 9092
  replicas: 3
  service:
    type: ClusterIP
    port: 9092

kafka_ui:
  image: "provectuslabs/kafka-ui:latest"
  port: 8080

flink:
  image: "flink:latest"
  port: 8081
  jobmanager:
    replicas: 1
    service:
      type: ClusterIP
      port: 8081